// Objective-C API for talking to github.com/b0ase/path402/apps/clawminer/mobile Go package.
//   gobind -lang=objc github.com/b0ase/path402/apps/clawminer/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * ExportWIF returns the current wallet's WIF private key.
Returns JSON: {"wif":"K..."} or {"error":"..."}.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileExportWIF(void);

/**
 * GenerateWallet creates a new random keypair, persists it, and replaces the current wallet.
Returns JSON: {"address":"...","public_key":"..."} or {"error":"..."}.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileGenerateWallet(void);

/**
 * GetAPIPort returns the port the HTTP API is listening on.
 */
FOUNDATION_EXPORT long MobileGetAPIPort(void);

/**
 * GetBlockByHash returns a single block by its hash.
Returns JSON: {"hash":"...",...} or {"error":"..."}.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileGetBlockByHash(NSString* _Nullable hash);

/**
 * GetBlockCount returns block counts as a JSON string.
Returns JSON: {"total":N,"own":M} or {"error":"..."}.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileGetBlockCount(void);

/**
 * GetBlocks returns recent PoI blocks as a JSON array.
Returns JSON: [{"hash":"...","height":N,...},...] or "[]".
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileGetBlocks(long limit);

/**
 * GetHeaderSyncStatus returns header sync status as a JSON string.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileGetHeaderSyncStatus(void);

/**
 * GetMiningStatus returns mining status as a JSON string.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileGetMiningStatus(void);

/**
 * GetStatus returns full daemon status as a JSON string.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileGetStatus(void);

/**
 * GetVersion returns the ClawMiner version string.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileGetVersion(void);

/**
 * ImportWallet loads a wallet from a WIF string and replaces the current wallet.
Returns JSON: {"address":"...","public_key":"..."} or {"error":"..."}.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileImportWallet(NSString* _Nullable wif);

/**
 * IsRunning returns true if the daemon is currently running.
 */
FOUNDATION_EXPORT BOOL MobileIsRunning(void);

/**
 * Start initialises and starts the ClawMiner daemon.
configYAML may be empty to use defaults. dataDir is the path to the app's
private files directory (e.g. Context.getFilesDir() + "/clawminer").
 */
FOUNDATION_EXPORT BOOL MobileStart(NSString* _Nullable configYAML, NSString* _Nullable dataDir, NSError* _Nullable* _Nullable error);

/**
 * Stop gracefully shuts down the daemon.
 */
FOUNDATION_EXPORT void MobileStop(void);

#endif
